### ISSUE TITLE
Extend Units

### ISSUE THREAD

**Issue by jrdiniz** [thombashi/humanreadable#1]
Hi,

Is it possible to extend the units to convert in minutes the input with sufix mn, like "12mn 41s"?

**Comment by thombashi** [comment]
Hi,

It is possible. However, I'm not so sure `mn` is a common abbreviation for minutes. I think that `m`/`min` would be more general abbreviation and you could use these.
Are there problems that existing abbreviations can't solve?

**Comment by thombashi** [comment]
Strings like `"12m40s"` are supported at `humanreadable 0.3.0`.
