### ISSUE TITLE
Typo in _time.py line 235

### ISSUE THREAD

**Issue by giobri** [thombashi/humanreadable#2]
```python
items.append(f"{int(self.days:d)}{_to_unit_str(self.Unit.DAY, style)}")
```

should be:

```python
items.append(f"{int(self.days)}{_to_unit_str(self.Unit.DAY, style)}")
```

**Comment by thombashi** [comment]
@giobri 
Thank you for your report.
Could you tell me which word contains the typo?
Your referenced code is a little bit different from the current implementation:

https://github.com/thombashi/humanreadable/blob/3bc18c9a7c2ab048c5b97eb2bc00af37154666af/humanreadable/_time.py#L235

And your suggested changes seem to be removed `:d`, that is Python formatting string.

**Comment by giobri** [comment]
I know but in this case the `:d` breaks the code.. I will reproduce the error and paste it here

On my side removing the `:d` formatting fixed the problem

**Comment by thombashi** [comment]
I understand your point.
You are reporting a bug that `Time.to_humanreadable()` failed when the value is over 1 day.
I fixed the bug.
